// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SDtvQgQM2oLU1An3NjXTSeR7iwQhjfQ',
    appId: '1:757376542158:web:d5769b862609bd32e4f79f',
    messagingSenderId: '757376542158',
    projectId: 'pegas-cash-collector',
    authDomain: 'pegas-cash-collector.firebaseapp.com',
    storageBucket: 'pegas-cash-collector.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoemQ8QdHEn69fLdK8zmGSjs6HhKlHWZo',
    appId: '1:757376542158:android:8c002662e52c9bade4f79f',
    messagingSenderId: '757376542158',
    projectId: 'pegas-cash-collector',
    storageBucket: 'pegas-cash-collector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACG4MvYNl1ZYZTikhkIxaYuD5s18y8O2Y',
    appId: '1:757376542158:ios:253eebf3f4056120e4f79f',
    messagingSenderId: '757376542158',
    projectId: 'pegas-cash-collector',
    storageBucket: 'pegas-cash-collector.firebasestorage.app',
    iosBundleId: 'com.example.pegasCashcollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACG4MvYNl1ZYZTikhkIxaYuD5s18y8O2Y',
    appId: '1:757376542158:ios:253eebf3f4056120e4f79f',
    messagingSenderId: '757376542158',
    projectId: 'pegas-cash-collector',
    storageBucket: 'pegas-cash-collector.firebasestorage.app',
    iosBundleId: 'com.example.pegasCashcollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2SDtvQgQM2oLU1An3NjXTSeR7iwQhjfQ',
    appId: '1:757376542158:web:81ad736b637f0a15e4f79f',
    messagingSenderId: '757376542158',
    projectId: 'pegas-cash-collector',
    authDomain: 'pegas-cash-collector.firebaseapp.com',
    storageBucket: 'pegas-cash-collector.firebasestorage.app',
  );
}
